[project]
name = "chatbot-memory-visualiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = ["openai>=1.92.3", "streamlit>=1.46.1"]
