[project]
name = "using-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.93.3",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.0",
]
