[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "openai>=1.82.0",
    "pillow>=11.2.1",
    "pydoll-python>=2.8.0",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
